### ISSUE TITLE
early check out should be failed

### ISSUE THREAD

**Issue by dqcode** [Capstone-campyuk/campyuk-FE#107]
https://user-images.githubusercontent.com/117468090/218270625-2bcd7207-cce0-433e-8e06-0e922e7e2642.mp4

**Comment by irfanfitriandi** [comment]
has been fixed

**Comment by diahrdn** [comment]
https://user-images.githubusercontent.com/116274338/218356374-b9e3f3bf-fc11-4ada-bb6a-b69a53829e0f.mov
